"""create forecasts table

Revision ID: 006570439c36
Revises: 5bf20b04ee47
Create Date: 2026-09-09 01:32:53.580702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006570439c36'
down_revision: Union[str, None] = '5bf20b04ee47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('forecast_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_point_count', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'subcategory', name='uq_forecasts_user_category_subcategory', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_forecasts_user_id'), 'forecasts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_user_id'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
