"""create profiles table

Revision ID: 665dfdb21536
Revises: e9503a32affd
Create Date: 2026-09-09 02:36:11.908849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665dfdb21536'
down_revision: Union[str, None] = 'e9503a32affd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='student', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('monthly_spending_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_savings_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weekly_study_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weekly_fitness_minutes', sa.Integer(), nullable=True),
    sa.Column('weekly_habit_completions', sa.Integer(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
