"""create entries table

Revision ID: a0f05d4f5936
Revises: e8248d03df69
Create Date: 2026-09-09 01:10:46.262442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f05d4f5936'
down_revision: Union[str, None] = 'e8248d03df69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_category'), 'entries', ['category'], unique=False)
    op.create_index(op.f('ix_entries_deleted_at'), 'entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_entries_occurred_at'), 'entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_entries_subcategory'), 'entries', ['subcategory'], unique=False)
    op.create_index('ix_entries_user_deleted_occurred', 'entries', ['user_id', 'deleted_at', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index('ix_entries_user_deleted_occurred', table_name='entries')
    op.drop_index(op.f('ix_entries_subcategory'), table_name='entries')
    op.drop_index(op.f('ix_entries_occurred_at'), table_name='entries')
    op.drop_index(op.f('ix_entries_deleted_at'), table_name='entries')
    op.drop_index(op.f('ix_entries_category'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
