"""add max_value to entries

Revision ID: fd81f6036f1d
Revises: c4d5e6f78901
Create Date: 2026-10-02 21:10:16.870441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd81f6036f1d'
down_revision: Union[str, None] = 'c4d5e6f78901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('max_value', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'max_value')
    # ### end Alembic commands ###
